apiVersion: apps/v1

kind: Deployment

metadata:
  name: ms-deployment

spec:
  selector:
    matchLabels:
      app: ms
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: ms
    spec:
      containers:
      - name: api-gateway
        image: api-gateway
        imagePullPolicy: Never # image is only avaliable locally 
        ports:
        - containerPort: 3000

      - name: service-a
        image: service-a
        imagePullPolicy: Never
        ports:
        - containerPort: 3001